openapi: 3.1.0
info:
  title: Gateway API
  description: API for processing payments through Fondy.
  version: 1.0.0
servers:
  - url: https://pay.fondy.eu/api
    description: Production server
paths:
  /checkout/url:
    post:
      tags:
      - Accept Payment
      summary: Accept Purchase
      description: This endpoint facilitates accepting payments via a hosted payment page. Merchants can use it to initiate a purchase process where customers are redirected to a secure payment page managed by Fondy. The hosted page simplifies compliance and security by handling the sensitive payment processing tasks, while allowing merchants to collect payments seamlessly. 
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptPurchaseRequest'
      responses:
        '200':
          description: "Different responses for successful transactions, interim transactions, or errors."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
              examples:
                final:
                  summary: "Final Response"
                  value:
                    order_id: "ID1234"
                    merchant_id: 1
                    amount: 1020
                    currency: "EUR"
                    order_status: "approved"
                    response_status: "success"
                    signature: "1773cf135bd89656131134b98637894dad42f808"
                    tran_type: "purchase"
                    sender_cell_phone: "+1234567890"
                    sender_account: "customer_account"
                    masked_card: "444444XXXXXX5555"
                    card_bin: 444444
                    card_type: "VISA"
                    rrn: "123456789"
                    approval_code: "654321"
                    response_code: 100
                    response_description: "Transaction approved"
                    reversal_amount: 0
                    settlement_amount: 1020
                    settlement_currency: "EUR"
                    order_time: "21.12.2014 11:21:30"
                    settlement_date: "21.12.2014"
                    eci: 5
                    fee: 10
                    payment_system: "card"
                    sender_email: "customer@example.com"
                    payment_id: 123456789012345
                    actual_amount: 1020
                    actual_currency: "EUR"
                    product_id: "hotel_booking_1234"
                    merchant_data: "custom_data"
                    verification_status: "verified"
                    rectoken: "da39a3ee5e6b4b0d3255bfef95601890afd80709"
                    rectoken_lifetime: "01.01.2018 00:00:00"
                    additional_info:
                      bank_name: "Some bank in US country"
                      bank_country: "US"
                      bank_response_code: "decln_1000"
                      card_product: "DEBIT"
                      card_category: "CLASSIC"
                      settlement_fee: 0.2
                      capture_status: "captured"
                      client_fee: 0.3
                      ipaddress_v4: "8.8.8.8"
                      capture_amount: 200
                      card_type: "VISA"
                      reservation_data: null
                      bank_response_description: "General decline"
                      transaction_id: 1058755083
                      timeend: "10.01.2018 11:21:30"
                      card_number: "4444555566661111"
                      payment_method: "apple"
                interim:
                  summary: "Interim Response"
                  value:
                    response_status: "success"
                    checkout_url: "https://pay.fondy.eu/checkout?token=e0a5d4f331806d1e2feb80353b4c44bf6751fc8c"
                    payment_id: 123456789012345
        '400':
          description: "Error response with details."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /3dsecure_step1:
    post:
      summary: Enroll Card in 3DSecure Service
      tags:
      - Accept Payment 3DS
      description: |
        This endpoint enables PCIDSS-compliant merchants to enroll a card in the 3DSecure service. By enrolling the card, the merchant initiates the 3DSecure verification process, adding an extra layer of authentication for online purchases. This service is only available to merchants who comply with PCI DSS (Payment Card Industry Data Security Standard) requirements.
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThreeDSecureStep1Request'
      responses:
        '200':
          description: "Card enrolled in 3DSecure service"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ThreeDSecureStep1Response'
  /3dsecure_step2:
    post:
      summary: Complete 3DSecure Payment
      tags:
      - Accept Payment 3DS
      description: |
        This endpoint is used to complete the 3DSecure payment process. Merchants should send the parameters received in the response from Step 1, along with additional required information, to finalize the 3DSecure enrollment with Fondy.
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ThreeDSecureStep2Request'
      responses:
        '200':
          description: "3DSecure payment completed successfully."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
              examples:
                final:
                  summary: "Success Response"
                  value:
                    order_id: "ID1234"
                    merchant_id: 1
                    amount: 1020
                    currency: "EUR"
                    order_status: "approved"
                    response_status: "success"
                    signature: "1773cf135bd89656131134b98637894dad42f808"
                    tran_type: "purchase"
                    sender_cell_phone: "+1234567890"
                    sender_account: "customer_account"
                    masked_card: "444444XXXXXX5555"
                    card_bin: 444444
                    card_type: "VISA"
                    rrn: "123456789"
                    approval_code: "654321"
                    response_code: 100
                    response_description: "Transaction approved"
                    reversal_amount: 0
                    settlement_amount: 1020
                    settlement_currency: "EUR"
                    order_time: "21.12.2014 11:21:30"
                    settlement_date: "21.12.2014"
                    eci: 5
                    fee: 10
                    payment_system: "card"
                    sender_email: "customer@example.com"
                    payment_id: 123456789012345
                    actual_amount: 1020
                    actual_currency: "EUR"
                    product_id: "hotel_booking_1234"
                    merchant_data: "custom_data"
                    verification_status: "verified"
                    rectoken: "da39a3ee5e6b4b0d3255bfef95601890afd80709"
                    rectoken_lifetime: "01.01.2018 00:00:00"
                    additional_info:
                      bank_name: "Some bank in US country"
                      bank_country: "US"
                      bank_response_code: "decln_1000"
                      card_product: "DEBIT"
                      card_category: "CLASSIC"
                      settlement_fee: 0.2
                      capture_status: "captured"
                      client_fee: 0.3
                      ipaddress_v4: "8.8.8.8"
                      capture_amount: 200
                      card_type: "VISA"
                      reservation_data: null
                      bank_response_description: "General decline"
                      transaction_id: 1058755083
                      timeend: "10.01.2018 11:21:30"
                      card_number: "4444555566661111"
                      payment_method: "apple"
        '400':
          description: "Error response with details."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /status/order_id:
    post:
      summary: Check Order Status
      tags:
      - Orders
      description: |
        This endpoint allows merchants to check the current status of an order through a host-to-host request. 
        The request can be made in JSON, XML, or HTML FORM format, and the response will be returned in the same format as the request. 
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckStatusRequest'
      responses:
        '200':
          description: "Order status response in the requested format (JSON, XML, or HTML FORM)."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
            text/html:
              schema:
                $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
  /reverse/order_id:
    post:
      summary: Order Reversal
      tags:
      - Orders
      description: |
        This endpoint allows merchants to reverse an order by sending a host-to-host request. 
        The request can be made in JSON, XML, or HTML FORM format, and the response will be returned in the same format.
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/OrderReversalRequest'
      responses:
        '200':
          description: "Order reversal response in the requested format (JSON, XML, or HTML FORM)."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OrderReversalResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/OrderReversalResponse'
            text/html:
              schema:
                $ref: '#/components/schemas/OrderReversalResponse'
  /api/transaction_list/:
    post:
      summary: Transaction List by Order
      tags:
      - Orders
      description: |
        Retrieves a list of transactions for a specified order ID. The request must include the `merchant_id`, `order_id`, and `signature` parameters to verify the request's authenticity.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TransactionListRequest'
      responses:
        '200':
          description: "List of transactions for the specified order."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TransactionListResponse'
  /api/recurring:
    post:
      summary: Purchase Using Card Token
      tags: 
      - Recurring Payment
      description: |
        This endpoint allows merchants to perform purchases using a stored card token. Additional parameter `rectoken` must be included.The request can be sent in JSON, XML, or HTML form format, and the response will match the request format.
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardTokenPurchaseRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/CardTokenPurchaseRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CardTokenPurchaseRequest'
      responses:
        '200':
          description: "Successful purchase response."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardTokenPurchaseResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CardTokenPurchaseResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/CardTokenPurchaseResponse'
        '400':
          description: "Error response with details."
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /api/checkout/redirect/:
    post:
      summary: Card Verification
      tags:
      - Card
      description: |
        This endpoint is used for card verification requests, which are generated by the merchant. The host-to-host request can be sent in HTML FORM, XML, or JSON format, and the response is always returned in the same content type as the request.
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CardVerificationRequest'
          application/xml:
            schema:
              $ref: '#/components/schemas/CardVerificationRequest'
          application/x-www-form-urlencoded:
            schema:
              $ref: '#/components/schemas/CardVerificationRequest'
        required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardVerificationResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CardVerificationResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/CardVerificationResponse'
        '400':
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /p2pcredit:
    post:
      tags:
        - Card
      summary: P2P Card Credit
      description: |
        This endpoint allows a merchant to perform a peer-to-peer (P2P) card credit transaction, transferring funds directly to a recipient's card number or a stored receiver token. The request must include either `receiver_card_number` or `receiver_rectoken`, along with transaction details such as `order_id`, `order_desc`, and `amount`.

        To secure this request, the merchant must generate a signature using their Credit private key specifically for `p2pcredit` operations.
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/P2pCreditRequest'
            application/xml:
              schema:
                $ref: '#/components/schemas/P2pCreditRequest'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/P2pCreditRequest'
          required: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CardVerificationResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CardVerificationResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/CardVerificationResponse'
        '400':
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /capture/order_id:
    post:
      tags:
        - Capture Pre-Purchase
      summary: Capture Pre-Authorized Payment
      description: |
        This endpoint allows a merchant to capture a previously pre-authorized amount on a card. The capture operation is the second stage in a two-stage payment scheme, where the initial amount was held during a pre-authorization request (`preauth = Y`). This capture can be a full or partial capture of the amount.

        > ðŸ“˜ Note
        > This operation applies only to card payments. If capture is not completed, only a reversal of the full held amount is available.
      parameters:
        - $ref: '#/components/parameters/ContentType'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CapturePrePurchaseRequest'
      responses:
        '200':
          description: Successful capture response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CapturePrePurchaseResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/CapturePrePurchaseResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/CapturePrePurchaseResponse'
        '400':
          description: Error Response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/xml:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
            application/x-www-form-urlencoded:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
components:
  parameters:
    ContentType:
      in: header
      name: Content-Type
      required: true
      schema:
        type: string
        enum:
          - application/json
          - application/xml
          - application/x-www-form-urlencoded
      description: Specifies the format for the request. Response will be in the same format.
  schemas:
    ErrorResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            response_status:
              type: string
              description: "Status indicating failure."
              example: "failure"
            error_message:
              type: string
              description: "Description of the error encountered."
              example: "General decline"
            error_code:
              type: integer
              description: "Error code for the failure."
              example: 1000
    AcceptPurchaseRequest:
      type: object
      required:
        - order_id
        - merchant_id
        - order_desc
        - signature
        - amount
        - currency
      properties:
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
          example: "ID1234"
        merchant_id:
          type: integer
          maxLength: 12
          description: "Merchant's unique identifier generated by Fondy during registration."
          example: 1
        order_desc:
          type: string
          maxLength: 1024
          description: "Description of the order in UTF-8 encoding."
          example: "Hotel booking â„–1234 Antalya Resort"
        signature:
          $ref: '#/components/schemas/Signature'
        amount:
          type: integer
          maxLength: 12
          description: "Order amount in cents, without separator. Example: 1020 (EUR) represents 10 euros and 20 cents."
          example: 1020
        currency:
          type: string
          maxLength: 3
          description: "Currency for the transaction (e.g., EUR, USD, GBP). Refer to the [Currencies](https://docs.fondy.eu/en/docs/page/27/) page for a full list of available currencies."
          $ref: '#/components/schemas/Currency'
          example: "EUR"
        version:
          type: string
          maxLength: 10
          default: "1.0.1"
          description: "Protocol version. If 1.0.1 is passed, `additional_info` parameter will be returned in callback."
          example: "1.0.1"
        response_url:
          type: string
          maxLength: 2048
          description: "URL where customer is redirected after payment completion."
          example: "http://site.com/responseurl"
        server_callback_url:
          $ref: '#/components/schemas/ServerCallbackUrl'
        payment_systems:
          type: string
          maxLength: 1024
          description: |
            Comma or semicolon separated list of allowed payment systems. Default value is set from merchant settings in Fondy merchant portal.

            Supported Values:

            | Payment system code | Description             |
            |---------------------|-------------------------|
            | `card`              | Visa/MasterCard/Maestro |
            | `banklinks_pl`      | Polland bank links      |
            | `banklinks_eu`      | European countries bank links |
            | `installments`      | Installments            |
          example: "card,banklinks_eu"
        default_payment_system:
          type: string
          maxLength: 25
          description: "Preferred payment system shown first to customer. Supported values are the same as for the `payment_systems` parameter above."
          example: "card"
        lifetime:
          type: integer
          maxLength: 9
          description: "Order lifetime in seconds. Default is 36000, max is 69120000."
          default: 36000
          example: 600
        merchant_data:
          type: string
          maxLength: 2048
          description: "Any data the merchant wants to receive in response callbacks and reports."
        preauth:
          $ref: '#/components/schemas/Preauth'
        sender_email:
          type: string
          maxLength: 254
          description: "Customer email address."
        descriptor:
          type: string
          maxLength: 21
          description: "Dynamic descriptor for transaction details."
        delayed:
          type: string
          maxLength: 1
          description: "Delayed order flag to control payment attempt behavior."
          enum:
            - Y  # Allows multiple attempts within the lifetime period
            - N  # Only one payment attempt allowed
          x-enumDescriptions:
            Y: "Allows the customer to pay the order within the period specified in the `lifetime` parameter. Multiple host-to-host callbacks and browser redirects may occur if the previous attempt failed."
            N: "If the payment is declined, the customer will be redirected to recreate the order. Only one callback will be sent to `server_callback_url`."
          default: Y
        lang:
          $ref: '#/components/schemas/Language'
        product_id:
          type: string
          maxLength: 1024
          description: Merchant product or service identifier.
        required_rectoken:
          type: string
          maxLength: 1
          description: "Flag indicating whether Fondy must return a card token for accessing funds without cardholder interaction."
          enum:
            - Y  # Return card token
            - N  # Do not return card token
          x-enumDescriptions:
            Y: "Fondy will return a card token for accessing card funds without cardholder interaction."
            N: "No card token will be returned."
          default: N
        verification:
          $ref: '#/components/schemas/Verification'
        verification_type:
          type: string
          maxLength: 25
          description: "Type of verification applied to the order."
          enum:
            - amount  # Hold amount on card
            - code    # Hold amount and require code entry
          x-enumDescriptions:
            amount: "The amount submitted by the merchant will be held on the card."
            code: "The amount will be held on the card, and the cardholder must enter a 4-character code to pass verification."
          default: amount
        rectoken:
          type: string
          maxLength: 40
          description: "Token for card access without cardholder interaction."
          example: "544d3f86237886b6404d8b000f6a7d71c45410b7"
        receiver_rectoken:
          type: string
          maxLength: 40
          description: "Token for card crediting without full card number."
        design_id:
          type: integer
          maxLength: 6
          description: "ID for checkout page design in merchant portal."
          example: 123
        subscription:
          type: string
          maxLength: 1
          description: "Flag to enable or disable scheduled payments."
          enum:
            - Y  # Enable scheduled payments
            - N  # Disable scheduled payments
          x-enumDescriptions:
            Y: "Enables scheduled payments for the order."
            N: "Disables scheduled payments for the order."
          default: N
        subscription_callback_url:
          type: string
          maxLength: 2048
          description: "URL for server callback after scheduled payment."
          example: "http://site.com/subscriptioncallback"
    Currency:
      type: string
      maxLength: 3
      enum:
        - AED  # U.A.E. Dirham
        - AFN  # Afghanistan Afghani
        - ALL  # Albanian LEK
        - AMD  # Armenian Dram
        - ANG  # Netherlands Antillia
        - AOA  # Angola Kwanza
        - ARS  # Argentine Peso
        - AUD  # Australian Dollar
        - AWG  # Aruban Guilder
        - AZN  # Azerbaijanian Manat
        - BAM  # Bosnian Conv. Mark
        - BBD  # Barbados Dollar
        - BDT  # Taka
        - BGN  # Bulgarian Lev
        - BHD  # Bahraini Dinar
        - BIF  # Burundi Franc
        - BMD  # Bermudan Dollar
        - BND  # Brunei Dollar
        - BOB  # Bolivian Peso
        - BRL  # Brazilian Real
        - BSD  # Bahamian Dollar
        - BTN  # Ngultrum
        - BWP  # Pula
        - BZD  # Belize Dollar
        - CAD  # Canadian Dollar
        - CDF  # Franc Congolais
        - CHF  # Swiss Franc
        - CLP  # Chilean Peso
        - CNY  # Yuan Renminbi
        - COP  # Colombian Peso
        - CRC  # Costa Rican Colon
        - CUP  # Cuban Peso
        - CVE  # Cape Verde Escudo
        - CZK  # Czech Koruna
        - DJF  # Djibouti Franc
        - DKK  # Danish Krone
        - DOP  # Dominican Peso
        - DZD  # Algerian Dinar
        - EGP  # Egyptian Pound
        - ERN  # Eritrean Nakfa
        - ETB  # Ethiopian Birr
        - EUR  # Euro
        - FJD  # Fiji Dollar
        - FKP  # Falkland Islands
        - GBP  # Pound Sterling
        - GEL  # Georgian Lari
        - GHS  # Ghana Cedi
        - GIP  # Gibraltar Pound
        - GMD  # Dalasi
        - GNF  # Syli
        - GTQ  # Quetzal
        - GYD  # Guyana Dollar
        - HKD  # Hong Kong Dollar
        - HNL  # Lempira
        - HRK  # Croatian Kuna
        - HTG  # Gourde
        - HUF  # Hungarian Forint
        - IDR  # Rupiah
        - ILS  # Israel Shekel
        - INR  # Indian Rupee
        - IQD  # Iraqi Dinar
        - IRR  # Iranian Rial
        - ISK  # Iceland Krona
        - JMD  # Jamaican Dollar
        - JOD  # Jordanian Dinar
        - JPY  # Japanese Yen
        - KES  # Kenyan Shilling
        - KGS  # Kyrgyzstan Som
        - KHR  # Riel
        - KMF  # Comoros Franc
        - KRW  # Korean Won
        - KWD  # Kuwaiti Dinar
        - KYD  # Cayman Island Dollar
        - KZT  # Tenge
        - LAK  # Kip
        - LBP  # Lebanese Pound
        - LKR  # Sri Lanka Rupee
        - LRD  # Liberian Dollar
        - LSL  # Lesotho Loti
        - LTL  # Lithuanian Litas
        - LVL  # Latvian Lat
        - LYD  # Libyan Dinar
        - MAD  # Moroccan Dirham
        - MDL  # Moldovan Leu
        - MGA  # Malagasy Ariary
        - MKD  # Macedonian Denar
        - MMK  # Kyat
        - MNT  # Tugrik
        - MOP  # Pataca
        - MUR  # Mauritius Rupee
        - MVR  # Maldivian Rupee
        - MWK  # Malawi Kwacha
        - MXN  # Mexican Peso
        - MYR  # Malaysian Ringgit
        - MZN  # Mozambique Metical
        - NAD  # Namibia Dollar
        - NGN  # Naira
        - NIO  # Cordoba
        - NOK  # Norwegian Krone
        - NPR  # Nepalese Rupee
        - NZD  # New Zealand Dollar
        - OMR  # Omani Rial
        - PAB  # Balboa
        - PEN  # Peruvian Sol
        - PGK  # Kina
        - PHP  # Philippine Peso
        - PKR  # Pakistani Rupee
        - PLN  # Polish Zloty
        - PYG  # Guarani
        - QAR  # Qatari Rial
        - RON  # New Romanian Leu
        - RSD  # Serbian Dinar
        - RWF  # Rwanda Franc
        - SAR  # Saudi Riyal
        - SBD  # Solomon Islands Dollar
        - SCR  # Seychelles Rupee
        - SDG  # Sudanese Pound
        - SEK  # Swedish Krona
        - SGD  # Singapore Dollar
        - SHP  # St. Helena Pound
        - SLL  # Leone
        - SOS  # Somali Shilling
        - SRD  # Surinamese Dollar
        - STD  # Dobra
        - SVC  # Salvadoran Colon
        - SZL  # Lilangeni
        - THB  # Thai Baht
        - TJS  # Tajik Somoni
        - TMT  # Turkmenistan Manat
        - TND  # Tunisian Dinar
        - TOP  # PaÊ»anga
        - TRY  # Turkish Lira
        - TTD  # Trinidad and Tobago Dollar
        - TWD  # New Taiwan Dollar
        - TZS  # Tanzanian Shilling
        - UAH  # Hryvnia
        - UGX  # Ugandan Shilling
        - USD  # United States Dollar
        - UYU  # Uruguayan Peso
        - UZS  # Uzbekistani Som
        - VEF  # Venezuelan BolÃ­var
        - VND  # Vietnamese Dong
        - VUV  # Vatu
        - WST  # Samoan Tala
        - XAF  # CFA Franc BEAC
        - XCD  # East Caribbean Dollar
        - XOF  # CFA Franc BCEAO
        - XPF  # CFP Franc
        - YER  # Yemeni Rial
        - ZAR  # South African Rand
        - ZMW  # Zambian Kwacha
        - ZWD  # Zimbabwean Dollar
    Language:
      lang:
        type: string
        maxLength: 2
        description: "Payment page's main language."
        enum:
          - ru  # Russian
          - uk  # Ukrainian
          - en  # English
          - lv  # Latvian
          - fr  # French
          - cs  # Czech
          - ro  # Romanian
          - it  # Italian
          - sk  # Slovak
          - pl  # Polish
          - es  # Spanish
          - hu  # Hungarian
          - de  # German
        x-enumDescriptions:
          ru: "Russian"
          uk: "Ukrainian"
          en: "English"
          lv: "Latvian"
          fr: "French"
          cs: "Czech"
          ro: "Romanian"
          it: "Italian"
          sk: "Slovak"
          pl: "Polish"
          es: "Spanish"
          hu: "Hungarian"
          de: "German"
        example: "en"
    Verification:
          type: string
          maxLength: 1
          description: "Flag indicating if the order should be automatically reversed by Fondy after successful approval."
          enum:
            - Y  # Auto-reverse order
            - N  # Do not auto-reverse order
          x-enumDescriptions:
            Y: "The order will be automatically reversed by Fondy after a successful approval."
            N: "The order will not be automatically reversed."
          default: N
    Preauth:
          type: string
          maxLength: 1
          description: "Preauthorization parameter for Visa/MasterCard payments to determine the timing of the charge."
          enum:
            - Y  # Hold amount
            - N  # Immediate debit
          x-enumDescriptions:
            Y: "The amount is held on the customerâ€™s card and not charged until the merchant sends a **capture** request to confirm."
            N: "The amount is debited from the customerâ€™s card immediately and settled to the merchant account, in accordance with settlement rules."
          default: N
    ServerCallbackUrl:
      type: string
      maxLength: 2048
      description: "URL for server-to-server callback post payment. See [Receiving Callbacks](https://docs.fondy.eu/en/docs/page/28/) for more details on callbacks."
      example: "http://site.com/callbackurl"
    Signature:
      type: string
      maxLength: 40
      description: |
        Signature for request verification, generated according to FONDYâ€™s algorithm. Required to verify merchant request consistency and authenticity.
        Learn how to use FONDYâ€™s algorithm at the [Signature Generation for Request and Response](https://docs.fondy.eu/en/docs/page/3/#chapter-3-5) page.
      example: "1773cf135bd89656131134b98637894dad42f808"
    AcceptPurchaseFinalResponse:
      type: object
      description: Parameters of the final response
      properties:
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
        merchant_id:
          type: integer
          maxLength: 12
          description: "Unique ID assigned to the merchant by Fondy."
        amount:
          type: integer
          maxLength: 12
          description: "Order amount in cents without separator."
        currency:
          $ref: '#/components/schemas/Currency'
        order_status:
          type: string
          maxLength: 50
          description: "Order processing status indicating the current state of the transaction."
          enum:
            - created       # Order created, awaiting payment details
            - processing    # Order processing by payment gateway
            - declined      # Order declined by Fondy, bank, or external system
            - approved      # Order completed, funds held and soon credited
            - expired       # Order lifetime expired
            - reversed      # Approved transaction was fully reversed
          x-enumDescriptions:
            created: "Order has been created, but the customer has not entered payment details yet; the merchant should continue to request the status of the order."
            processing: "Order is still processing by the payment gateway; the merchant should continue to request the status of the order."
            declined: "Order is declined by Fondy, a bank, or an external payment system."
            approved: "Order completed successfully, funds are held on the payerâ€™s account and soon will be credited to the merchant; the merchant can provide the service or ship goods."
            expired: "Order lifetime expired."
            reversed: "Previously approved transaction was fully reversed. In this case, the `reversal_amount` will equal `actual_amount`."
        response_status:
          type: string
          maxLength: 50
          description: "Request processing status (e.g., 'success' or 'failure')."
        signature:
          type: string
          maxLength: 40
          description: "Order signature for request verification."
        tran_type:
          type: string
          maxLength: 50
          enum: ["purchase", "verification", "p2p credit", "p2p transfer", "settlement", "reverse"]
        sender_cell_phone:
          type: string
          maxLength: 16
          description: "Customer's mobile phone number."
        sender_account:
          type: string
          maxLength: 50
          description: "Customer payment account."
        masked_card:
          type: string
          maxLength: 19
          description: "Masked card number."
        card_bin:
          type: integer
          maxLength: 6
          description: "First 6 digits of the card number."
        card_type:
          type: string
          maxLength: 50
          enum: ["VISA", "MasterCard"]
        rrn:
          type: string
          maxLength: 50
          description: "Bank transaction ID, often not unique."
        approval_code:
          type: string
          maxLength: 6
          description: "Authorization code returned by the bank."
        response_code:
          type: integer
          maxLength: 4
          description: "Order decline response code."
        response_description:
          type: string
          maxLength: 1024
          description: "Description of the response code."
        reversal_amount:
          type: integer
          maxLength: 12
          description: "Total reversal amount for the current order."
        settlement_amount:
          type: integer
          maxLength: 12
          description: "Settlement amount for the current order."
        settlement_currency:
          $ref: '#/components/schemas/Currency'
        order_time:
          type: string
          format: date-time
          description: "Order creation date in DD.MM.YYYY hh:mm:ss format."
        settlement_date:
          type: string
          format: date
          description: "Settlement date in DD.MM.YYYY format."
        eci:
          type: integer
          maxLength: 2
          description: "Ecommerce Indicator for 3DSecure authentication status."
          enum: [5, 6, 7]
        fee:
          type: integer
          maxLength: 12
          description: "Fee charged by Fondy."
        payment_system:
          type: string
          maxLength: 50
          description: "Payment system used for the transaction."
        sender_email:
          type: string
          maxLength: 254
          description: "Customer's email address."
        payment_id:
          type: integer
          maxLength: 19
          description: "Unique payment ID generated by Fondy."
        actual_amount:
          type: integer
          maxLength: 12
          description: "Actual amount held or charged from the card."
        actual_currency:
          $ref: '#/components/schemas/Currency'
        product_id:
          type: string
          maxLength: 1024
          description: "Merchant's product or service ID."
        merchant_data:
          type: string
          maxLength: 2048
          description: "Arbitrary data sent by the merchant in the request."
        verification_status:
          type: string
          maxLength: 50
          description: "Code verification result."
          enum: ["verified", "incorrect", "failed", "created"]
        rectoken:
          type: string
          maxLength: 40
          description: "Token for accessing card funds without cardholder interaction."
        rectoken_lifetime:
          type: string
          format: date-time
          description: "Token expiration date in DD.MM.YYYY hh:mm:ss format."
        additional_info:
          type: object
          description: "Additional information in JSON format."
          properties:
            bank_name:
              type: string
              description: "Bank name."
            bank_country:
              type: string
              description: "Bank country."
            bank_response_code:
              type: string
              description: "Response code from the bank."
            card_product:
              type: string
              description: "Type of card product."
            card_category:
              type: string
              description: "Category of the card."
            settlement_fee:
              type: number
              description: "Settlement fee."
            capture_status:
              type: string
              description: "Status of the capture."
            client_fee:
              type: number
              description: "Fee charged to the client."
            ipaddress_v4:
              type: string
              description: "IP address in IPv4 format."
            capture_amount:
              type: integer
              description: "Amount captured."
            card_type:
              type: string
              enum: ["VISA", "MasterCard"]
              description: "Type of the card used."
            reservation_data:
              type: string
              description: "Reservation data."
            bank_response_description:
              type: string
              description: "Description of the bank's response."
            transaction_id:
              type: integer
              description: "Transaction ID from the bank."
            timeend:
              type: string
              format: date-time
              description: "End time for the transaction."
            card_number:
              type: string
              description: "Card number used."
            payment_method:
              type: string
              enum: ["apple", "googlepay", "card"]
              description: "Payment method used."
    ThreeDSecureStep1Request:
      type: object
      required:
      - order_id
      - merchant_id
      - order_desc
      - signature
      - amount
      - currency
      - card_number
      - cvv2
      - expiry_date
      - client_ip
      properties:
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
          example: "ID1234"
        merchant_id:
          type: integer
          maxLength: 12
          description: "Unique ID assigned to the merchant by Fondy."
          example: 1
        order_desc:
          type: string
          maxLength: 1024
          description: "Order description in UTF-8."
          example: "Hotel booking â„–1234 Antalia Resort"
        signature:
          $ref: '#/components/schemas/Signature'
        amount:
          type: integer
          maxLength: 12
          description: "Order amount in cents without separator."
          example: 1020
        currency:
          $ref: '#/components/schemas/Currency'
        card_number:
          type: string
          maxLength: 19
          description: "Visa/MC card number."
        cvv2:
          type: string
          maxLength: 4
          description: "Card CVV2/CVC2 code."
        expiry_date:
          type: string
          pattern: "^(0[1-9]|1[0-2])([0-9]{2})$"
          description: "Card expiry date in MMYY format."
        client_ip:
          type: string
          maxLength: 15
          description: "Client IP address."
        version:
          type: string
          maxLength: 10
          description: "Protocol version."
          default: "1.0.1"
          example: "1.0.1"
        server_callback_url:
          $ref: '#/components/schemas/ServerCallbackUrl'
        lifetime:
          type: integer
          maxLength: 6
          description: "Order lifetime in seconds. Defaults to 600, maximum 69120000."
          default: 600
          example: 600
        merchant_data:
          type: string
          maxLength: 2048
          description: "Data that merchant wants to receive in callback or response."
        preauth:
          $ref: '#/components/schemas/Preauth'
        sender_email:
          type: string
          maxLength: 50
          description: "Customer email."
        descriptor:
          type: string
          maxLength: 21
          description: "Dynamic descriptor for transaction."
        lang:
          $ref: '#/components/schemas/Language'
        product_id:
          type: string
          maxLength: 1024
          description: "Merchant product or service ID."
        verification:
          $ref: '#/components/schemas/Verification'
        container:
          type: string
          description: "Google/Apple Pay encrypted data in BASE64 encoding."
          example: "ewogICJhcGlWZXJzaW9uTWlub3IiOiAwLAogICJhcGlWZXJzaW9uIjogMiw..."
    ThreeDSecureStep1Response:
      type: object
      properties:
        response_status:
          type: string
          maxLength: 50
          description: "If no error occurred, this field always returns 'success'."
          example: "success"
        acs_url:
          type: string
          maxLength: 2048
          description: "URL of the cardholder's issuing bank's Access Control Server, where the customer must enter the 3DSecure password."
          example: "https://pay.fondy.eu/checkout?token=e0a5d4f331806d1e2feb80353b4c44bf6751fc8c"
        pareq:
          type: string
          maxLength: 20480
          description: "Parameter which must be submitted to `acs_url`."
        md:
          type: string
          maxLength: 1024
          description: "Unique 3DSecure request ID generated by Fondy payment gateway."
      example:
        response_status: "success"
        acs_url: "https://pay.fondy.eu/checkout?token=e0a5d4f331806d1e2feb80353b4c44bf6751fc8c"
        pareq: "PaReq_content_here"
        md: "unique_3dsecure_request_id"
    ThreeDSecureStep2Request:
      type: object
      required:
      - order_id
      - merchant_id
      - pares
      - md
      - signature
      properties:
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
          example: "ID1234"
        merchant_id:
          type: integer
          maxLength: 12
          description: "Unique merchant ID assigned by Fondy."
          example: 1
        pares:
          type: string
          maxLength: 20480
          description: "Parameter returned by the issuing bank to the specified URL after password verification."
        md:
          type: string
          maxLength: 1024
          description: "Unique 3DSecure request ID generated by Fondy."
        version:
          type: string
          maxLength: 10
          description: "Protocol version."
          default: "1.0"
          example: "1.0"
        signature:
          $ref: '#/components/schemas/Signature'
      example:
        order_id: "ID1234"
        merchant_id: 1
        pares: "PaRes_content_from_bank"
        md: "unique_3dsecure_request_id"
        version: "1.0"
        signature: "1773cf135bd89656131134b98637894dad42f808"
    CheckStatusRequest:
      type: object
      required:
        - order_id
        - merchant_id
        - signature
      properties:
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
          example: "ID1234"
        merchant_id:
          type: integer
          maxLength: 12
          description: "Unique ID assigned to the merchant by Fondy."
          example: 1
        signature:
          $ref: '#/components/schemas/Signature'
        version:
          type: string
          maxLength: 10
          description: "Protocol version. Default is 1.0."
          example: "1.0"
    OrderReversalRequest:
      type: object
      required:
        - order_id
        - merchant_id
        - signature
        - amount
        - currency
      properties:
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
          example: "ID1234"
        merchant_id:
          type: integer
          maxLength: 12
          description: "Unique ID assigned to the merchant by Fondy."
          example: 1
        signature:
          $ref: '#/components/schemas/Signature'
        version:
          type: string
          maxLength: 10
          description: "Protocol version. Default is 1.0."
          example: "1.0"
        amount:
          type: integer
          maxLength: 12
          description: "Reversal amount in cents without separator (e.g., 1020 for 10 euros and 20 cents)."
          example: 1020
        currency:
          $ref: '#/components/schemas/Currency'
        comment:
          type: string
          maxLength: 1024
          description: "Merchant's comment on the reversal reason in UTF-8."
          example: "Customer returned product back."
    OrderReversalResponse:
      type: object
      properties:
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
          example: "ID1234"
        merchant_id:
          type: integer
          maxLength: 12
          description: "Unique ID assigned to the merchant by Fondy."
          example: 1
        revers_status:
          type: string
          maxLength: 50
          description: "Reversal processing status."
          enum: ["created", "declined", "approved"]
        response_status:
          type: string
          maxLength: 50
          description: "Request processing status. Returns 'success' if validation passes, otherwise 'failure'."
          example: "success"
        signature:
          $ref: '#/components/schemas/Signature'
        response_code:
          type: integer
          maxLength: 4
          description: "Response decline code, if applicable."
          example: 1008
        response_description:
          type: string
          maxLength: 1024
          description: "Description of the response decline reason."
          example: "Parameter `amount` is mandatory."
    TransactionListRequest:
      type: object
      properties:
        merchant_id:
          type: integer
          maxLength: 12
          description: "Merchant unique ID, assigned by Fondy during registration."
          example: 1
        order_id:
          type: string
          maxLength: 1024
          description: "Order ID generated by the merchant."
          example: "order_12345_12.10.2018:11:05"
        signature:
          $ref: '#/components/schemas/Signature'
      required:
        - merchant_id
        - order_id
        - signature
    TransactionListResponse:
      type: object
      properties:
        response:
          type: array
          description: "List of transactions for the specified order."
          items:
            type: object
            properties:
              verification_code:
                type: string
                nullable: true
                description: "Verification code, if applicable."
                example: null
              masked_card:
                type: string
                description: "Masked card number."
                example: "408093XXXXXX8221"
              protocol:
                type: string
                description: "Protocol used for the transaction."
                example: "safe_charge"
              pares_status:
                type: string
                nullable: true
                description: "3D Secure Pares status."
                example: null
              sender_country:
                type: string
                description: "Sender's country."
                example: "US"
              istest:
                type: string
                description: "Indicates if the transaction is a test ('Y' or 'N')."
                example: "N"
              timestart:
                type: string
                format: date-time
                description: "Transaction start time."
                example: "17.02.2017 13:50:32"
              currency:
                type: string
                description: "Transaction currency."
                example: "USD"
              preauth:
                type: string
                description: "Indicates if the transaction is preauthorized ('Y' or 'N')."
                example: "N"
              transaction_status:
                type: string
                description: "Current status of the transaction."
                example: "declined"
              duration:
                type: integer
                description: "Duration of the transaction in seconds."
                example: 953
              ip_country:
                type: string
                description: "IP country of the sender."
                example: "US"
              settlement_amount:
                type: integer
                description: "Settlement amount for the transaction."
                example: 0
              timeend:
                type: string
                format: date-time
                description: "Transaction end time."
                example: "17.02.2017 13:50:33"
              order_id:
                type: string
                description: "Order ID related to the transaction."
                example: "13986590658a6e385e2c26"
              actual_amount:
                type: number
                description: "Actual amount involved in the transaction."
                example: 33.7
              ipaddress_v4:
                type: string
                description: "Sender's IPv4 address."
                example: "45.56.154.162"
              expire_year:
                type: string
                description: "Expiration year of the payment card."
                example: "2019"
              actual_currency:
                type: string
                description: "Actual currency of the transaction."
                example: "USD"
              tran_type:
                type: string
                description: "Transaction type (e.g., 'purchase')."
                example: "purchase"
              payment_system:
                type: string
                description: "Payment system used (e.g., 'card')."
                example: "card"
              merchant_id:
                type: integer
                description: "Merchant ID associated with the transaction."
                example: 1397308
              response_description:
                type: string
                description: "Description of the response or error message."
                example: "General decline"
              payment_id:
                type: integer
                description: "Unique ID of the payment."
                example: 37877547
              card_type:
                type: string
                description: "Type of card used in the transaction."
                example: "VISA"
              amount:
                type: number
                description: "Transaction amount."
                example: 33.7
              sender_email:
                type: string
                nullable: true
                description: "Email of the sender."
                example: null
              response_code:
                type: integer
                description: "Response code of the transaction."
                example: 1000
    CardTokenPurchaseRequest:
      allOf:
        - $ref: '#/components/schemas/AcceptPurchaseRequest'
        - type: object
          required:
            - rectoken
    CardTokenPurchaseResponse:
      $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
    CardVerificationRequest:
      allOf:
        - $ref: '#/components/schemas/AcceptPurchaseRequest'
        - type: object
          required:
            - verification
            - verification_type
    CardVerificationResponse:
      $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
    P2pCreditRequest:
      allOf:
        - $ref: '#/components/schemas/AcceptPurchaseRequest'
        - type: object
          required:
            - receiver_card_number
            - receiver_rectoken
    P2pCreditResponse:
      $ref: '#/components/schemas/AcceptPurchaseFinalResponse'
    CapturePrePurchaseRequest:
      type: object
      properties:
        order_id:
          type: string
          description: Unique identifier for the order.
          example: "ID1234"
        merchant_id:
          type: integer
          description: Unique identifier for the merchant, generated by Fondy.
          example: 1
        signature:
          type: string
          description: Signature to verify request consistency and authenticity.
          example: "1773cf135bd89656131134b98637894dad42f808"
        version:
          type: string
          description: Protocol version.
          default: "1.0"
        amount:
          type: integer
          description: Amount to capture in the smallest unit of currency (e.g., cents).
          example: 1020
        currency:
          type: string
          description: Currency of the transaction (e.g., USD, EUR, GBP, UAH).
          example: "USD"
      required:
        - order_id
        - merchant_id
        - signature
        - amount
        - currency
    CapturePrePurchaseResponse:
      type: object
      properties:
        response:
          type: object
          properties:
            order_id:
              type: string
              description: Unique identifier for the order.
              example: "test309906285"
            response_status:
              type: string
              description: Processing status, success if request parameters pass validation.
              example: "success"
            response_code:
              type: string
              description: Code for response status.
              example: ""
            capture_status:
              type: string
              description: Capture processing status, indicating if the capture was successful or declined.
              example: "captured"
            response_description:
              type: string
              description: Reason for the response decline if applicable.
              example: ""
            merchant_id:
              type: integer
              description: Unique identifier for the merchant.
              example: 1









